#!/usr/bin/env bash
# Transfers a file from a client to a server

# Verify if all parameters are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

filepath=$1
serverip=$2
username=$3
sshkey=$4

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$sshkey" "$filepath" "$username@$serverip:~/"

exit 0
