#!/usr/bin/env bash
# Configures a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y

NAME=$(hostname)

sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    add_header X-Served-By $NAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location /404 {
        root /var/www/html;
	internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
