#!/usr/bin/env bash
# Setups up and configures a load balancer

sudo apt-get update -y
sudo apt-get install -y haproxy


echo "global
    log 127.0.0.1 local0 notice
    maxconn 2048
    user haproxy
    group haproxy
defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option http-server-close
    option http-pretend-keepalive
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000
frontend myfrontend
    bind *:80
    default_backend mybackend
backend mybackend
    balance roundrobin
    server 316681-web-01 54.160.68.240:80 check
    server 316681-web-02 34.232.71.122:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
